tas2580_sitemap_sitemapindex:
    pattern: /sitemap.xml
    defaults: { _controller: tas2580.sitemap.sitemap:index }
tas2580_sitemap_sitemap:
    pattern: /sitemap-{id}.xml
    defaults: { _controller: tas2580.sitemap.sitemap:sitemap }
