services:
    tas2580.sitemap.sitemap:
        class: tas2580\sitemap\controller\sitemap
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @controller.helper
            - @dispatcher
            - %core.php_ext%
            - @ext.manager
